title:              Graphic Recording
email:              your-email@example.com
description:        Aoyama Gakuin University - furuhashi lab-
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "furuhashilab.github.io/startbootstrap-clean-blog-jekyll/"

# Social Profiles
twitter_username:   
github_username:   
facebook_username:  



# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
